### ISSUE TITLE
运行或编译报错找不到模块

### ISSUE THREAD

**Issue by defsky** [mudclient/go-mud#16]
在手机上termux中启用go module 后，运行go run main.go或者go build main.go都会报错:
build command-line-arguments: cannot find module for path golang.org/x/sys/unix

**Comment by dzpao** [comment]
你需要先安装项目依赖的前置模块。
安装方法：
`go get ./...`

**Comment by defsky** [comment]
> 你需要先安装项目依赖的前置模块。
> 安装方法：
> `go get ./...`

go get 安装都提示好了，实际上$GOPATH这个路径下是有这个模块的，编译还是不行

**Comment by dzpao** [comment]
@defsky 有空了再试一下。应该已经解决了。

源码安装方法：
```
go get -u github.com/dzpao/go-mud
```

**Comment by dzpao** [comment]
先关闭了。如果有问题，你可以重新打开。 @defsky
