### ISSUE TITLE
i和sk查看技能列表显示不正常

### ISSUE THREAD

**Issue by defsky** [mudclient/go-mud#18]
linux系统里面，用i和sk命令查看列表显示不正常，下面是截图
![1](https://user-images.githubusercontent.com/15100900/61674407-4f299b00-ad26-11e9-8485-91a6b6519e5f.png)
![2](https://user-images.githubusercontent.com/15100900/61674950-cceea600-ad28-11e9-8aaf-f0140c31b048.png)

**Comment by dzpao** [comment]
这个是依赖的第三方库的问题，正在和作者沟通中。我自己本地改好了，你用编译好的二进制，那个应该没问题。

**Comment by dzpao** [comment]
已经解决。先关闭了。

@defsky 请知晓。
