### ISSUE TITLE
quit 指令作用域不正确

### ISSUE THREAD

**Issue by zhenzh** [mudclient/go-mud#22]
在游戏中使用 quit 命令的结果是退出 gomud 而不是退出游戏，导致 quit 后游戏人物在游戏中处于断线状态

**Comment by dzpao** [comment]
是的。这个 BUG 我也发现了。v0.6.0 中已经解决。

**Comment by dzpao** [comment]
补充一下，关于 quit 和 exit 两个命令，目前的设计是这样的：

* 交互模式下输入 quit 和 exit 会退出 GoMud，但不会向服务器发送该指令，以防止意外的游戏人物角色 quit。这是 feature，不是 BUG。之前有个版本是会同时向服务器发送 quit 或 exit，导致人物角色掉线，背包清空，已改正。
* 目前正在设计脚本语言，语法类似于 TinTin，脚本语言中将会提供 `#send` 指令来向服务器发送文字，届时可以用 `#send quit` 和 `#send exit` 来向服务器发送 quit 和 exit 指令。
* 目前版本中，可以通过服务器 alias 指令，设置 quit 的别名，例如 `alias QUIT quit`，然后通过输入 `QUIT` 来向服务器发送指令以指示退出游戏人物角色。
